baseURL = 'https://docilemango.github.io/'
languageCode = 'en-us'
title = 'DocileMango'
theme = "hugo-blog-awesome"

[[params.socialIcons]]
name = "github"
url = "https://github.com/DocileMango"

[[params.socialIcons]]
name  = "linkedin"
url = "https://www.linkedin.com/in/james-montesines-684507238/"

[params]
    goToTop = true
    profileImage = "img/mango.png"
    customCSS = ["css/custom.css"]

[menu]
    [[menu.main]]
    identifier = "blogs"
    name = "Blogs"
    url = "/blogs/"

    [[menu.main]]
    identifier = "ctf"
    name = "CTFs"
    url = "/ctf/"

    [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects"

    [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"